### PR TITLE
fix(lsposed): increase time of notifications

### LINKED ISSUE #82: Bug: уведомления перекрывают друг друга
Android 15, Xiaomi 15, прошивка xiaomi.eu 2.0.216.0
При сохранении идёт запрос к Magisk, в ответ приходит уведомление "root-права предоставлены", одновременно с этим приложение присылает свое уведомление с подтверждением сохранения. Из-за наложения уведомления, текст не получается прочитать

Image

### PR DESCRIPTION
**Pull request by AndreyGubin**
### Why
When saving, a request is sent to Magisk, which responds with a "root access granted" notification. At the same time, the app shows its own notification confirming the save. These two notifications overlap, making the text unreadable.

### Summary
- Notification time increased to make it readable

Closes #82

### CODE REVIEW

File: lsposed/app/src/main/kotlin/dev/okhsunrog/vpnhide/PortsHidingScreen.kt [hunk 1]
```diff
@@ -262,33 +266,47 @@ fun PortsHidingScreen(
...
+                            Text(stringResource(R.string.btn_save))
+                        }
                     }
+
+//                    SnackbarHost(
+//                        hostState = snackbarHostState,
+//                        modifier = Modifier
+//                            .fillMaxWidth()
+//                            .align(Alignment.TopCenter),
+//                    )
```
Comment (okhsunrog) [inline lsposed/app/src/main/kotlin/dev/okhsunrog/vpnhide/PortsHidingScreen.kt]: Could you remove this one?

**Review by okhsunrog — CHANGES_REQUESTED** [review]
Thanks! Could you add a changelog entry as described in https://github.com/okhsunrog/vpnhide/blob/main/CONTRIBUTING.md ?
And remove the commented out code.

File: lsposed/app/src/main/kotlin/dev/okhsunrog/vpnhide/PortsHidingScreen.kt (hunk 1 above)
Comment (AndreyGubin) [reply lsposed/app/src/main/kotlin/dev/okhsunrog/vpnhide/PortsHidingScreen.kt]: Fixed

**Review by okhsunrog — APPROVED** [review]
LGTM, thanks!
